### ISSUE TITLE
Cannot load driver [ProcHideDrv]

### ISSUE THREAD

**Issue by miguellealperez** [daem0nc0re/VectorKernel#1]
Hello, I am new to this world, I am learning from your projects and having a troubleshooting with loading driver ProcHideDrv. I have learning so many things, but rn I am over load, can not process myself, so I appreciate your help.
1. Compiled driver-Release.X64:
![image](https://github.com/daem0nc0re/VectorKernel/assets/112134240/7116dd61-9de1-4831-b27c-9343bb05679d)
`Driver cert was installed on Trusted Root Certification Authorities  --> Said "This certificate is OK."`
2. Creating SC for the driver:
![image](https://github.com/daem0nc0re/VectorKernel/assets/112134240/01ce2d2d-946a-451f-9e45-2fabe1e8504c)
`There is when I stay stuck, because seems I did all good.`
3. Checking all can be possible.
![image](https://github.com/daem0nc0re/VectorKernel/assets/112134240/13a75d20-063c-4f5e-9967-dcae4e541d16)
![image](https://github.com/daem0nc0re/VectorKernel/assets/112134240/814c259c-c93b-49f0-bfde-b9665fa2d7bc)
![image](https://github.com/daem0nc0re/VectorKernel/assets/112134240/05d8312f-fcc3-40ca-994f-c394a0c280f5)
`I have checked that all the way was clean to proceed, but still can not.`
Maybe I am doing something wrong, hope your knowledge can help me. Thanks.
Regards, Miguel

**Comment by miguellealperez** [comment]
Or maybe is this the problem?
![image](https://github.com/daem0nc0re/VectorKernel/assets/112134240/8d322f9f-919a-4015-ae72-fde1d3bd023c)

**Comment by miguellealperez** [comment]
Thank you a lot, work by 1. 
![image](https://github.com/daem0nc0re/VectorKernel/assets/112134240/eca62716-653a-4e5a-8d46-b2266b8f2df0)

For the history:
1. Disable UEFI secure boot on BIOS.
2. CMD Admin rights --> `Bcdedit.exe -set TESTSIGNING ON` 
3.  Restart computer, then Windows is in test mode.
![image](https://github.com/daem0nc0re/VectorKernel/assets/112134240/3aa6d101-974e-4fdd-9142-2924eebd3a71)
4. All set to start learning.

Also, other source explain too. https://stackoverflow.com/questions/63622996/startservice-failed-577-self-signed-kernel-driver-how-to-fix

**Comment by daem0nc0re** [comment]
Thanks for positive feedback!
I will add your issue for windows kernel beginners later
